### ISSUE TITLE
Textual Error & Training Failure

### ISSUE THREAD

**Issue by Jzzzi** [hustvl/DiffusionDrive#10]
#  Textual Error & Training Failure

This is an outstanding project! However, I encountered a couple of issues while trying to train the model.

### Error 1

In the `navsim/agents/diffusiondrive/modules/multimodal_loss.py` file, there appears to be a textual error on line 7. The import statement should be modified from follows:

```python
from navsim.agents.diffdriver.transfuser_config import TransfuserConfig
```

It should instead be:

```python
from navsim.agents.diffusiondrive.transfuser_config import TransfuserConfig
```

### Error 2
I noticed that all the scripts in the 'download' folder have CRLF line endings, rather than the LF line endings supported by Linux systems. This causes the scripts to fail when executed on a Linux machine.

## **Issue 2: Training Failure**

I was able to run the following command successfully:

```bash
python navsim/planning/script/run_dataset_caching.py agent=diffusiondrive_agent experiment_name=training_diffusiondrive_agent train_test_split=navtrain
```

However, when trying to run the training command:

```bash
python $NAVSIM_DEVKIT_ROOT/navsim/planning/script/run_training.py \
    agent=diffusiondrive_agent \
    experiment_name=training_diffusiondrive_agent  \
    train_test_split=navtrain  \
    split=trainval   \
    trainer.params.max_epochs=100 \
    cache_path="${NAVSIM_EXP_ROOT}/training_cache/" \
    use_cache_without_dataset=True  \
    force_cache_computation=False
```

The training process stops at the following point:

```bash
| Name  | Type            | Params
------------------------------------------
0 | agent | TransfuserAgent | 60.7 M
------------------------------------------
60.7 M    Trainable params
320       Non-trainable params
60.7 M    Total params
242.863   Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                                                    | 0/167 [00:00<?, ?it/s]
```

Then, the following error message appears:

```bash
Error executing job with overrides: ['agent=diffusiondrive_agent', 'experiment_name=training_diffusiondrive_agent', 'train_test_split=navtrain', 'split=trainval', 'trainer.params.max_epochs=100', 'cache_path=/data114/DiffusionDrive/exp/training_cache/', 'use_cache_without_dataset=True', 'force_cache_computation=False']
Traceback (most recent call last):
  File "/data114/DiffusionDrive/navsim/planning/script/run_training.py", line 134, in main
    trainer.fit(
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1303, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 152, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 270, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 239, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/amp.py", line 80, in optimizer_step
    closure_result = closure()
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 129, in closure
    step_output = self._step_fn()
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 318, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 642, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 635, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/data114/DiffusionDrive/navsim/planning/training/agent_lightning_module.py", line 40, in training_step
    return self._step(batch, "train")
  File "/data114/DiffusionDrive/navsim/planning/training/agent_lightning_module.py", line 28, in _step
    prediction = self.agent.forward(features)
  File "/data114/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 107, in forward
    return self._transfuser_model(features,targets=targets)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data114/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 132, in forward
    trajectory = self._trajectory_head(trajectory_query,agents_query, cross_bev_feature,bev_spatial_shape,status_encoding[:, None],targets=targets,global_img=None)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data114/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 453, in forward
    return self.forward_train(ego_query, agents_query, bev_feature,bev_spatial_shape,status_encoding,targets,global_img)
  File "/data114/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 494, in forward_train
    trajectory_loss = self.loss_computer(poses_reg, poses_cls, targets, plan_anchor)
  File "/data114/DiffusionDrive/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data114/DiffusionDrive/navsim/agents/diffusiondrive/modules/multimodal_loss.py", line 133, in forward
    target_traj = targets["trajectory"]
TypeError: 'NoneType' object is not subscriptable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

It seems that the `targets` object is `None`, and it causes a `TypeError` when trying to access `targets["trajectory"]`. Could you please help me understand how to resolve this issue?

**Thanks a lot!**

**Comment by LegendBC** [comment]
Thanks for providing the information and solution! I have fixed the bugs in the latest commit.

**Comment by varunjammula** [comment]
the train script should be as follows:
 python navsim/planning/script/run_training.py \
        agent=diffusiondrive_agent \
        experiment_name=training_diffusiondrive_agent  \
        train_test_split=navtrain  \
        split=trainval   \
        trainer.params.max_epochs=100 \
        cache_path="${NAVSIM_EXP_ROOT}/training_cache/" \
        use_cache_without_dataset=True  \
        force_cache_computation=False
