### ISSUE TITLE
Diffuser Issue

### ISSUE THREAD

**Issue by BlueCat-de** [hustvl/DiffusionDrive#14]
Hi! 
While I'm running run_dataset_caching.py, the following error occurs:
```
Traceback (most recent call last):
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 117, in ray_map
    results = _ray_map_items(task, *item_lists, log_dir=log_dir)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 100, in _ray_map_items
    for object_id, output in tqdm(_ray_object_iterator(object_ids), total=len(object_ids), desc='Ray objects'):
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 28, in _ray_object_iterator
    yield next_id, ray.get(next_id)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InstantiationException): ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
AttributeError: module 'navsim.agents.diffusiondrive' has no attribute 'transfuser_agent'

During handling of the above exception, another exception occurred:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 12, in <module>
    from navsim.agents.diffusiondrive.transfuser_model_v2 import V2TransfuserModel as TransfuserModel
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 10, in <module>
    from diffusers.schedulers import DDIMScheduler
ModuleNotFoundError: No module named 'diffusers'

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent':
ModuleNotFoundError("No module named 'diffusers'")
Are you sure that 'transfuser_agent' is importable from module 'navsim.agents.diffusiondrive'?

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 43, in wrapped_fn
    return fn(*args, **kwargs)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 38, in cache_features
    agent: AbstractAgent = instantiate(cfg.agent)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent', see chained exception above.
full_key: agent
Error executing job with overrides: ['agent=diffusiondrive_agent', 'experiment_name=training_diffusiondrive_agent', 'train_test_split=mini']
Traceback (most recent call last):
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 117, in ray_map
    results = _ray_map_items(task, *item_lists, log_dir=log_dir)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 100, in _ray_map_items
    for object_id, output in tqdm(_ray_object_iterator(object_ids), total=len(object_ids), desc='Ray objects'):
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 28, in _ray_object_iterator
    yield next_id, ray.get(next_id)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InstantiationException): ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
AttributeError: module 'navsim.agents.diffusiondrive' has no attribute 'transfuser_agent'

During handling of the above exception, another exception occurred:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 12, in <module>
    from navsim.agents.diffusiondrive.transfuser_model_v2 import V2TransfuserModel as TransfuserModel
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 10, in <module>
    from diffusers.schedulers import DDIMScheduler
ModuleNotFoundError: No module named 'diffusers'

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent':
ModuleNotFoundError("No module named 'diffusers'")
Are you sure that 'transfuser_agent' is importable from module 'navsim.agents.diffusiondrive'?

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 43, in wrapped_fn
    return fn(*args, **kwargs)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 38, in cache_features
    agent: AbstractAgent = instantiate(cfg.agent)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent', see chained exception above.
full_key: agent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 94, in main
    _ = worker_map(worker, cache_features, data_points)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/worker_utils.py", line 33, in worker_map
    scattered_objects = worker.map(Task(fn=fn), object_chunks)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py", line 117, in map
    return self._map(task, *aligned_item_lists, verbose=verbose)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/utils/multithreading/worker_ray_no_torch.py", line 154, in _map
    return ray_map(task, *item_lists, log_dir=self._log_dir)  # type: ignore
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 122, in ray_map
    raise RuntimeError(exc)
RuntimeError: ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
AttributeError: module 'navsim.agents.diffusiondrive' has no attribute 'transfuser_agent'

During handling of the above exception, another exception occurred:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 12, in <module>
    from navsim.agents.diffusiondrive.transfuser_model_v2 import V2TransfuserModel as TransfuserModel
  File "/root/projects/E2E/DiffusionDrive/navsim/agents/diffusiondrive/transfuser_model_v2.py", line 10, in <module>
    from diffusers.schedulers import DDIMScheduler
ModuleNotFoundError: No module named 'diffusers'

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent':
ModuleNotFoundError("No module named 'diffusers'")
Are you sure that 'transfuser_agent' is importable from module 'navsim.agents.diffusiondrive'?

The above exception was the direct cause of the following exception:

ray::wrapped_fn() (pid=56893, ip=10.96.151.7)
  File "/root/projects/E2E/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 43, in wrapped_fn
    return fn(*args, **kwargs)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 38, in cache_features
    agent: AbstractAgent = instantiate(cfg.agent)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent', see chained exception above.
full_key: agent

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

And it seems that two issues contribute to this error:
* ImportError: Error loading 'navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent':
ModuleNotFoundError("No module named 'diffusers'").
* AttributeError: module 'navsim.agents.diffusiondrive' has no attribute 'transfuser_agent'.

But I think that the AttributeError occurs due to the ImportError. So have you ever faced this "No module named 'diffusers'" error? Thanks!

I carefully followed the installation instruction, and I'm pretty sure that all environment requirements are satisfied.

**Comment by BlueCat-de** [comment]
`python3 -m pip install diffusers` solved this issue.

**Comment by chan-yuu** [comment]
I'm using `diffusers==0.24.0` and `huggingface_hub==0.19.4`
